### ISSUE TITLE
Mistake in step 1

### ISSUE THREAD

**Issue by majamanojlovic** [raspberrypilearning/sonic-pi-install#13]
Feedback from volunteers:

The following sentence needs to be updated: _Click the 'Download MSI Installer' button._

The button now says: Windows 10 (64 bit) MSI Installer. It should also be noted that the MSI Installer also works on Windows 8.1. And Windows 7 is end-of-life and doesn't have to be supported anymore.

Also, the image _msi-installer.png_ needs to be updated to reflect this.

**Comment by MarcScott** [comment]
fixed
